// TMDB public image CDN - works in browser without API key
const TMDB = 'https://image.tmdb.org/t/p/w342';

const HOLLYWOOD = [
  { name:"The Dark Knight",       year:2008, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg", emoji:"🦇" },
  { name:"Inception",             year:2010, genre:"scifi",     poster:"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg", emoji:"🌀" },
  { name:"Interstellar",          year:2014, genre:"scifi",     poster:"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", emoji:"🌌" },
  { name:"Avengers: Endgame",     year:2019, genre:"action",    poster:"https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg", emoji:"🦸" },
  { name:"Parasite",              year:2019, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY0LWE2ZTgtOThmNDBjZGRjODM3XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg", emoji:"🏚️" },
  { name:"Joker",                 year:2019, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZTctZTgyNDk1MDQzODc1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", emoji:"🃏" },
  { name:"La La Land",            year:2016, genre:"romance",   poster:"https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg", emoji:"💛" },
  { name:"Dune",                  year:2021, genre:"scifi",     poster:"https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg2YzYtYTkzN2JkZTg1ZTU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", emoji:"🏜️" },
  { name:"Whiplash",              year:2014, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", emoji:"🥁" },
  { name:"Get Out",               year:2017, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc1MTI@._V1_SX300.jpg", emoji:"😱" },
  { name:"Everything Everywhere All at Once", year:2022, genre:"scifi", poster:"https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg", emoji:"🥯" },
  { name:"Mad Max: Fury Road",    year:2015, genre:"action",    poster:"https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", emoji:"🚗" },
  { name:"John Wick",             year:2014, genre:"action",    poster:"https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX300.jpg", emoji:"🐶" },
  { name:"The Notebook",          year:2004, genre:"romance",   poster:"https://m.media-amazon.com/images/M/MV5BODcwNWE3OTMtMDc3MS00NDFjLWE1OTAtNDU3OGVlNjdjYjk0XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"💌" },
  { name:"Forrest Gump",          year:1994, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", emoji:"🏃" },
  { name:"Superbad",              year:2007, genre:"comedy",    poster:"https://m.media-amazon.com/images/M/MV5BMTc0NjIyMjA2OF5BMl5BanBnXkFtZTcwMzIxNDE1MQ@@._V1_SX300.jpg", emoji:"🍺" },
  { name:"The Social Network",    year:2010, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", emoji:"💻" },
  { name:"Knives Out",            year:2019, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxZGM0Y2IwOTdjXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg", emoji:"🔪" },
  { name:"Spider-Man: Into the Spider-Verse", year:2018, genre:"animation", poster:"https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg", emoji:"🕷️" },
  { name:"Spirited Away",         year:2001, genre:"animation", poster:"https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", emoji:"🧙" },
  { name:"Titanic",               year:1997, genre:"romance",   poster:"https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg", emoji:"🚢" },
  { name:"Her",                   year:2013, genre:"romance",   poster:"https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg", emoji:"📱" },
  { name:"Black Panther",         year:2018, genre:"action",    poster:"https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg", emoji:"👑" },
  { name:"The Grand Budapest Hotel", year:2014, genre:"comedy", poster:"https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg", emoji:"🏨" },
  { name:"Oppenheimer",           year:2023, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg", emoji:"💥" },
  { name:"Barbie",                year:2023, genre:"comedy",    poster:"https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg", emoji:"💗" },
  { name:"Top Gun: Maverick",     year:2022, genre:"action",    poster:"https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg", emoji:"✈️" },
  { name:"Hereditary",            year:2018, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BOTU0NzkwMjgxNl5BMl5BanBnXkFtZTgwMDQ2NjU2NjM@._V1_SX300.jpg", emoji:"🕯️" },
  { name:"Your Name",             year:2016, genre:"animation", poster:"https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZjRhZi00YjlkLTg1YjYtMzI2MzUxNzQyYmY0XkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_SX300.jpg", emoji:"⭐" },
  { name:"Moana",                 year:2016, genre:"animation", poster:"https://m.media-amazon.com/images/M/MV5BMjI4MzU5NTExNF5BMl5BanBnXkFtZTgwNzY1MTEwMDI@._V1_SX300.jpg", emoji:"🌊" },
];

const BOLLYWOOD = [
  { name:"3 Idiots",              year:2009, genre:"comedy",    poster:"https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🎓" },
  { name:"Dangal",                year:2016, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BMjQ3OTgzMzY2NV5BMl5BanBnXkFtZTgwODY1MDI2MDI@._V1_SX300.jpg", emoji:"🤼" },
  { name:"Andhadhun",             year:2018, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BZWZhMjhhZmYtOTIzOC00MGYzLWI1OGYtM2ZkN2IxNTI4ZWI3XkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_SX300.jpg", emoji:"🎹" },
  { name:"Gully Boy",             year:2019, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BNDc4NTgxNzQ0M15BMl5BanBnXkFtZTgwMDc1NTA2NzM@._V1_SX300.jpg", emoji:"🎤" },
  { name:"Kabir Singh",           year:2019, genre:"romance",   poster:"https://m.media-amazon.com/images/M/MV5BZTQwNWMzMWYtYmM3Ny00MDgxLTg4NTAtNjA1MzY3MDgyNzNiXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg", emoji:"💔" },
  { name:"Dil Chahta Hai",        year:2001, genre:"comedy",    poster:"https://m.media-amazon.com/images/M/MV5BNzgwOTQ4OTYtYTc0OC00ZTgwLThhMDYtOGM4Y2YzNDJkODFiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🌊" },
  { name:"Zindagi Na Milegi Dobara", year:2011, genre:"drama",  poster:"https://m.media-amazon.com/images/M/MV5BNjI2NWI4YmItMTc3My00MDI4LWEwZDctZmJkZDNiYjgwMzc4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🏖️" },
  { name:"Queen",                 year:2014, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BNjA3YTgzNTMtMGQ4My00NTMxLThjODktN2M4OGM4NTAyZjYyXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg", emoji:"👸" },
  { name:"Gangs of Wasseypur",    year:2012, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BNGMwNzUwNjYtNTkzNi00ZjQ4LWI5ZWMtYzA4ZjRlODAwNzMwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg", emoji:"🔫" },
  { name:"PK",                    year:2014, genre:"comedy",    poster:"https://m.media-amazon.com/images/M/MV5BMTYzOTE2NjkxN15BMl5BanBnXkFtZTgwMDgzMTg0MzE@._V1_SX300.jpg", emoji:"👽" },
  { name:"Dilwale Dulhania Le Jayenge", year:1995, genre:"romance", poster:"https://m.media-amazon.com/images/M/MV5BZjdjYTFmNy00MjlhLWJjYzAtNGEyZDY1OGMtZTQ4ODZjZGZhYjE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🌻" },
  { name:"Lagaan",                year:2001, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BNTMzMzYxNjktYjU5Yi00NzQ4LTkxZjktYzVlNWVmZTQ3YWUyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🏏" },
  { name:"Taare Zameen Par",      year:2007, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BMDIzZjk1NTktZDAxMC00ZjM3LWE5YjQtNTQzYjMxMGQzNjMwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🎨" },
  { name:"Swades",                year:2004, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BZDkzNTkxNjEtYTllZC00YzQxLTk1MzAtNWFkMWQ1NWZkMGVjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🇮🇳" },
  { name:"Rockstar",              year:2011, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BMTQ4OTYwMjA0Ml5BMl5BanBnXkFtZTcwNjcxOTQxNw@@._V1_SX300.jpg", emoji:"🎸" },
  { name:"Barfi!",                year:2012, genre:"comedy",    poster:"https://m.media-amazon.com/images/M/MV5BYzM2NTkwNTctNTgwMi00NDQxLWEwYzgtZGM1MWQ5YmFmNjQ5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg", emoji:"🎪" },
  { name:"Tumbbad",               year:2018, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BYmQxNjZkN2ItM2U4Yy00MDk4LWEzYWMtMTdhYmZlZDQ1YmQ5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", emoji:"🌧️" },
  { name:"URI: The Surgical Strike", year:2019, genre:"action", poster:"https://m.media-amazon.com/images/M/MV5BMjAyNDQwOTA0NF5BMl5BanBnXkFtZTgwNTE4NzkwNzM@._V1_SX300.jpg", emoji:"🎖️" },
  { name:"Drishyam",              year:2015, genre:"thriller",  poster:"https://m.media-amazon.com/images/M/MV5BNmNhODYzNTktYTZiYy00YzViLTkzMDktZDhiMDE5NzA1ZjZhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg", emoji:"👁️" },
  { name:"Rang De Basanti",       year:2006, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BYWM3YTkwNjEtMzc5Yi00MTMwLWJkZWYtNWZlNWExMGVkNmI4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🌺" },
  { name:"Animal",                year:2023, genre:"action",    poster:"https://m.media-amazon.com/images/M/MV5BNmY3NGQ4ZGItNzgwYy00YTYyLWJhMTEtN2NkYzFhMjAyYWYwXkEyXkFqcGdeQXVyMTUzNTgzNzM@._V1_SX300.jpg", emoji:"🐺" },
  { name:"Pathaan",               year:2023, genre:"action",    poster:"https://m.media-amazon.com/images/M/MV5BNzgzYWQ4NTEtMjY2YS00YzU5LWI5YjAtNjkxZTg2YWZmZGQ1XkEyXkFqcGdeQXVyMTUzNTgzNzM@._V1_SX300.jpg", emoji:"💥" },
  { name:"Masaan",                year:2015, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BNjZiMGMzZGYtODZiNy00MWFiLTkzNmUtOTg1NTkzNmVmNWFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", emoji:"🔥" },
  { name:"Kho Gaye Hum Kahan",    year:2023, genre:"drama",     poster:"https://m.media-amazon.com/images/M/MV5BNGNhZmY3ZTQtM2Y1Yy00NGNmLThlNTgtZGFkNzRlMzdjNGE4XkEyXkFqcGdeQXVyMTUzNTgzNzM@._V1_SX300.jpg", emoji:"📱" },
];

const HW_GENRES = ['all','action','drama','thriller','scifi','comedy','romance','animation'];
const BW_GENRES = ['all','drama','thriller','action','comedy','romance'];

const ALL_SONGS = [
  { title:"Power",                  artist:"Kanye West",           emoji:"⚡", vibe:"hype",      mood:"🔥 Hype",      genres:["action","thriller"] },
  { title:"Blinding Lights",        artist:"The Weeknd",           emoji:"🌃", vibe:"hype",      mood:"🔥 Hype",      genres:["action","romance"] },
  { title:"Lose Yourself",          artist:"Eminem",               emoji:"🎤", vibe:"hype",      mood:"🔥 Hype",      genres:["drama","action"] },
  { title:"HUMBLE.",                artist:"Kendrick Lamar",        emoji:"👑", vibe:"hype",      mood:"🔥 Hype",      genres:["thriller","drama"] },
  { title:"Chaiyya Chaiyya",        artist:"AR Rahman",            emoji:"🚂", vibe:"hype",      mood:"🔥 Hype",      genres:["drama","romance"] },
  { title:"Zinda",                  artist:"Siddharth Mahadevan",  emoji:"🏋️", vibe:"hype",      mood:"🔥 Hype",      genres:["action","drama"] },
  { title:"Kar Har Maidaan Fateh",  artist:"Sukhwinder Singh",     emoji:"🎖️", vibe:"hype",      mood:"🔥 Hype",      genres:["drama","action"] },
  { title:"Electric Feel",          artist:"MGMT",                 emoji:"⚡", vibe:"chill",     mood:"🌊 Chill",     genres:["scifi","animation"] },
  { title:"The Less I Know",        artist:"Tame Impala",          emoji:"🌀", vibe:"chill",     mood:"🌊 Chill",     genres:["scifi","romance"] },
  { title:"Redbone",                artist:"Childish Gambino",     emoji:"🌿", vibe:"chill",     mood:"🌊 Chill",     genres:["thriller","drama"] },
  { title:"Sunflower",              artist:"Post Malone",          emoji:"🌻", vibe:"chill",     mood:"🌊 Chill",     genres:["animation","comedy"] },
  { title:"Iktara",                 artist:"Amit Trivedi",         emoji:"🎶", vibe:"chill",     mood:"🌊 Chill",     genres:["romance","drama"] },
  { title:"Kabira",                 artist:"Tochi Raina",          emoji:"☁️", vibe:"chill",     mood:"🌊 Chill",     genres:["romance","drama"] },
  { title:"Skinny Love",            artist:"Bon Iver",             emoji:"🍂", vibe:"emotional", mood:"💧 Emotional", genres:["drama","romance"] },
  { title:"All of Me",              artist:"John Legend",          emoji:"💌", vibe:"emotional", mood:"💧 Emotional", genres:["romance","drama"] },
  { title:"Numb",                   artist:"Linkin Park",          emoji:"💢", vibe:"emotional", mood:"💧 Emotional", genres:["drama","thriller"] },
  { title:"Tujh Mein Rab Dikhta Hai", artist:"Roop Kumar Rathod", emoji:"🌹", vibe:"emotional", mood:"💧 Emotional", genres:["romance","drama"] },
  { title:"Channa Mereya",          artist:"Arijit Singh",         emoji:"💔", vibe:"emotional", mood:"💧 Emotional", genres:["romance","drama"] },
  { title:"Ae Dil Hai Mushkil",     artist:"Arijit Singh",         emoji:"🎸", vibe:"emotional", mood:"💧 Emotional", genres:["romance","drama"] },
  { title:"Bad Guy",                artist:"Billie Eilish",        emoji:"😈", vibe:"dark",      mood:"🌑 Dark",      genres:["thriller","drama"] },
  { title:"505",                    artist:"Arctic Monkeys",       emoji:"🚬", vibe:"dark",      mood:"🌑 Dark",      genres:["thriller","romance"] },
  { title:"Starboy",                artist:"The Weeknd",           emoji:"🌠", vibe:"dark",      mood:"🌑 Dark",      genres:["scifi","thriller"] },
  { title:"Tum Ho",                 artist:"Mohit Chauhan",        emoji:"🌑", vibe:"dark",      mood:"🌑 Dark",      genres:["romance","thriller"] },
  { title:"Happy",                  artist:"Pharrell Williams",    emoji:"😄", vibe:"happy",     mood:"☀️ Happy",     genres:["comedy","animation"] },
  { title:"Shake It Off",           artist:"Taylor Swift",         emoji:"✨", vibe:"happy",     mood:"☀️ Happy",     genres:["comedy","romance"] },
  { title:"Golden Hour",            artist:"JVKE",                 emoji:"🌅", vibe:"happy",     mood:"☀️ Happy",     genres:["romance","comedy"] },
  { title:"Badtameez Dil",          artist:"Shalmali Kholgade",    emoji:"🎉", vibe:"happy",     mood:"☀️ Happy",     genres:["comedy","romance"] },
  { title:"London Thumakda",        artist:"Labh Janjua",          emoji:"💃", vibe:"happy",     mood:"☀️ Happy",     genres:["comedy","romance"] },
  { title:"Senorita",               artist:"Shaan",                emoji:"🌞", vibe:"happy",     mood:"☀️ Happy",     genres:["comedy","romance"] },
];
